import type { ProfessionCategory } from '../types.js';

export const professionCategoryByProfession: Record<string, ProfessionCategory> = {
  Activist: 'activist',
  Actor: 'entertainer',
  Admiral: 'military-figure',
  Archbishop: 'religious-figure',
  Archduke: 'royal-family',
  Artist: 'artist',
  Astronomer: 'scientist',
  'Basketball player': 'sportsperson',
  Bushranger: 'criminal-outlaw',
  Businessman: 'business-figure',
  Chairman: 'politician',
  Composer: 'entertainer',
  Conqueror: 'military-figure',
  Cricketer: 'sportsperson',
  'Cult leader': 'religious-figure',
  Daimyo: 'royal-family',
  Diarist: 'writer',
  Dictator: 'politician',
  Diplomat: 'politician',
  'Drug lord': 'criminal-outlaw',
  Emperor: 'royal-family',
  Explorer: 'explorer',
  'Fashion designer': 'artist',
  Footballer: 'sportsperson',
  General: 'military-figure',
  Inventor: 'scientist',
  Liberator: 'revolutionary',
  Mathematician: 'scientist',
  'Military leader': 'military-figure',
  Musician: 'entertainer',
  Mystic: 'religious-figure',
  Naturalist: 'scientist',
  Novelist: 'writer',
  'Opposition leader': 'politician',
  Painter: 'artist',
  Philosopher: 'philosopher',
  Physicist: 'scientist',
  Playwright: 'writer',
  'Political activist': 'activist',
  'Political leader': 'politician',
  Politician: 'politician',
  Pope: 'religious-figure',
  President: 'politician',
  'Prime minister': 'politician',
  Queen: 'royal-family',
  'Racing driver': 'sportsperson',
  Rapper: 'entertainer',
  Revolutionary: 'revolutionary',
  'Royal figure': 'royal-family',
  Scientist: 'scientist',
  Singer: 'entertainer',
  Statesman: 'politician',
  Tsar: 'royal-family',
  Unknown: 'other',
  Wrestler: 'sportsperson',
  Writer: 'writer',
};

const professionCategoryByPersonId: Record<string, ProfessionCategory> = {
  'che-guevara': 'politician',
  'mahatma-gandhi': 'politician',
  'vladimir-lenin': 'politician',
  'simon-bolivar': 'politician',
};

export const getProfessionCategory = (
  profession: string,
  personId?: string,
): ProfessionCategory =>
  personId
    ? (professionCategoryByPersonId[personId] ?? professionCategoryByProfession[profession] ?? 'other')
    : (professionCategoryByProfession[profession] ?? 'other');
